// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lrrkhpboasorryofdlvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxycmtocGJvYXNvcnJ5b2ZkbHZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwODU3NTUsImV4cCI6MjA2NDY2MTc1NX0.DTIryk-MNJ9LEdCXOXimbevXd95w_6NGK0TXp-8XaxE";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);